on: push
name: Build PDF on push
jobs:
  run-latex:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: Book-Poly.tex
        args: -pdf -file-line-error -e '$max_repeat=10' -interaction=nonstopmode
        latexmk_shell_escape: true
        post_compile: "mv Book-Poly.pdf poly-book.pdf && mkdir output/ && cp poly-book.pdf output/poly-book.pdf"
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.SERVER_FTP_ADDRESS }}
        username: ${{ secrets.SERVER_FTP_USERNAME }}
        password: ${{ secrets.SERVER_FTP_PASSWORD }}
        server-dir: ${{ github.event.repository.name }}/
        exclude: .git*
          - .git*/**
          -  **/.git*/**
        log-level: verbose
    - name: Deploy to build branch
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: pdf
        FOLDER: output
