on: push
name: Build PDF on push
jobs:
  run-latex:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: Book-Poly.tex
        latexmk_shell_escape: true
        post_compile: "mkdir output/ && mv Book-Poly.pdf output/poly-book.pdf"
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.SERVER_FTP_ADDRESS }}
        username: ${{ secrets.SERVER_FTP_USERNAME }}
        password: ${{ secrets.SERVER_FTP_PASSWORD }}
        local-dir: output/
        state-name: ../.ftp-deploy-sync-state.json
        server-dir: poly-book/
        exclude: .git*
          - .git*/**
          -  **/.git*/**
        log-level: verbose
